### ISSUE TITLE
OrientDB Gremlin server not working in python

### ISSUE THREAD

**Issue by Akshay-15mca1098** [orientechnologies/orientdb-gremlin#146]
I know this is not a good place to post this question but I need to find the answer.
 
I am using the orientdb and gremlin server in python, Gremlin server started successfully, but when I am trying to add a vertex to the orientdb through gremlin code it's giving me an error.

`query = """graph.addVertex(label, "Test", "title", "abc", "title", "abc")"""`

following is the Traceback

```
Traceback (most recent call last):
  File "/home/shubham/Documents/bitbucket/ecodrone/ecodrone/test.py", line 7, in <module>
    print(execute_query("""graph.addVertex(label, "Test", "title", "abc", "title", "abc")"""))
  File "/home/shubham/Documents/bitbucket/ecodrone/ecodrone/base_gremlin.py", line 47, in execute_query
    results = future_results.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/shubham/.local/lib/python3.5/site-packages/gremlin_python/driver/resultset.py", line 81, in cb
    f.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/shubham/.local/lib/python3.5/site-packages/gremlin_python/driver/connection.py", line 77, in _receive
    self._protocol.data_received(data, self._results)
  File "/home/shubham/.local/lib/python3.5/site-packages/gremlin_python/driver/protocol.py", line 106, in data_received
    "{0}: {1}".format(status_code, data["status"]["message"]))
gremlin_python.driver.protocol.GremlinServerError: 599: Error during serialization: Direct self-reference leading to cycle (through reference chain: com.orientechnologies.orient.core.id.ORecordId["identity"])
```

**Comment by maggiolo00** [comment]
Hi @Akshay-15mca1098 

which version of OrientDB?

**Comment by Akshay-15mca1098** [comment]
OrientDB 3.2.3

**Comment by Akshay-15mca1098** [comment]
I don't know I am on the right path but I followed this [post](https://groups.google.com/forum/#!topic/gremlin-users/YOmjLbl9ObY). According to that, I downloaded some jar files `bin/gremlin-server.sh -i com.michaelpollmeier orientdb-gremlin 3.2.3.0 ` but now, when I tried to install 3.3.0 version it gives me an error.

**Comment by Akshay-15mca1098** [comment]
how can I install Gremlin Driver version 3.0.2?

**Comment by Akshay-15mca1098** [comment]
is there any documentation to configure all requirements

**Comment by Akshay-15mca1098** [comment]
Hi @maggiolo00 I tried to start the server but some GraphFactory error I get. is there anything i have to download?. also I attached a screenshot for more clarity
![image](https://user-images.githubusercontent.com/29207885/41584873-0f33f206-73c6-11e8-8808-781e61f91145.png)

**Comment by maggiolo00** [comment]
Hi @Akshay-15mca1098 

can you share your configuration?

**Comment by maggiolo00** [comment]
@Akshay-15mca1098 

about docs. I'm updating it now

**Comment by Akshay-15mca1098** [comment]
gremlin : apache-tinkerpop-gremlin-server-3.3.1
OrientDB: orientdb-tp3-3.0.2
gremlinpython : 3.3.0
For download jar files use this `bin/gremlin-server.sh -i com.orientechnologies orientdb-gremlin 3.0.2`

**Comment by maggiolo00** [comment]
@Akshay-15mca1098 

can you share `gremlin-server-orientdb.yaml` and `orientdb-empty.properties`?

Thanks

**Comment by Akshay-15mca1098** [comment]
gremlin-server-orientdb.yaml file
```
host: localhost
port: 8182
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphs: {
  graph : conf/orientdb-empty.properties
}
scriptEngines: {
  gremlin-groovy: {
    plugins: { org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.orientdb.jsr223.OrientDBGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
               org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [../config/demodb.groovy]}}}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { ioRegistries: [org.apache.tinkerpop.gremlin.orientdb.io.OrientIoRegistry] }}             # application/vnd.gremlin-v3.0+gryo
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}                                                                       # application/vnd.gremlin-v3.0+gryo-stringd
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.apache.tinkerpop.gremlin.orientdb.io.OrientIoRegistry] }}         # application/json
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
  - { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000}}
strictTransactionManagement: false
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536
authentication: {
  authenticator: com.orientechnologies.tinkerpop.server.auth.OGremlinServerAuthenticator
    }
ssl: {
  enabled: false}
```
orientdb-empty.properties file

`gremlin.graph=org.apache.tinkerpop.gremlin.orientdb.OrientEmbeddedFactory`

also, I tried with also

`gremlin.graph=org.apache.tinkerpop.gremlin.orientdb.OrientGraph`

**Comment by maggiolo00** [comment]
@Akshay-15mca1098 
Ok let me try

**Comment by maggiolo00** [comment]
@Akshay-15mca1098 

does the install 

```
bin/gremlin-server.sh -i com.orientechnologies orientdb-gremlin 3.0.2
```

succeed?

**Comment by Akshay-15mca1098** [comment]
yes

**Comment by maggiolo00** [comment]
i have this error while trying to install the driver in a gremlin server

```sh
wolfwood@:apache-tinkerpop-gremlin-server-3.3.1$ bin/gremlin-server.sh -i com.orientechnologies orientdb-gremlin 3.0.2
Redirecting to 'install com.orientechnologies orientdb-gremlin 3.0.2' (-i will be removed in a future release)
Installing dependency com.orientechnologies orientdb-gremlin 3.0.2
Could not install the dependency: Error grabbing Grapes -- [download failed: org.apache.tinkerpop#gremlin-shaded;3.3.0!gremlin-shaded.jar]
java.lang.RuntimeException: Error grabbing Grapes -- [download failed: org.apache.tinkerpop#gremlin-shaded;3.3.0!gremlin-shaded.jar]
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at groovy.grape.GrapeIvy.getDependencies(GrapeIvy.groovy:424)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at groovy.grape.GrapeIvy.resolve(GrapeIvy.groovy:571)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at groovy.grape.GrapeIvy.resolve(GrapeIvy.groovy:534)
	at groovy.grape.Grape.resolve(Grape.java:202)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at org.apache.tinkerpop.gremlin.groovy.util.DependencyGrabber.copyDependenciesToPath(DependencyGrabber.groovy:110)
	at org.apache.tinkerpop.gremlin.server.util.GremlinServerInstall.main(GremlinServerInstall.java:38)
```

**Comment by Akshay-15mca1098** [comment]
Working in my system 

![image](https://user-images.githubusercontent.com/29207885/41591753-418f5102-73d8-11e8-9a00-0e90758cd165.png)

**Comment by Akshay-15mca1098** [comment]
Is there any other way please let me know. I am not tied up with this installation.

**Comment by maggiolo00** [comment]
Hi @Akshay-15mca1098 

the correct implementation for the Graph is

```
gremlin.graph=org.apache.tinkerpop.gremlin.orientdb.OrientFactory
```

Then i think you need to change 

```
{files: [../config/demodb.groovy]}
```
That binds `g` traversal to globals

You can use `empty-sample.groovy` in the scripts directory

**Comment by Akshay-15mca1098** [comment]
okay let me try this

**Comment by Akshay-15mca1098** [comment]
Hi @maggiolo00  after changes it was successfully configured with the property but some more error occurs. Is it working in your system

```
[INFO] DefaultGraphManager - Graph [graph] was successfully configured via [conf/orientdb-empty.properties].
[INFO] ServerGremlinExecutor - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
Exception in thread "main" java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.initializeGremlinScriptEngineManager(GremlinExecutor.java:448)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.<init>(GremlinExecutor.java:105)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.<init>(GremlinExecutor.java:74)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor$Builder.create(GremlinExecutor.java:590)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:128)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:111)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.main(GremlinServer.java:325)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.initializeGremlinScriptEngineManager(GremlinExecutor.java:434)
	... 6 more
Caused by: java.lang.IllegalArgumentException: java.io.FileNotFoundException: ../conf/scripts/empty-sample.groovy
	at org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin$Builder.files(ScriptFileGremlinPlugin.java:68)
	... 11 more
Caused by: java.io.FileNotFoundException: ../conf/scripts/empty-sample.groovy
	... 12 more
```

**Comment by Akshay-15mca1098** [comment]
what I understood you are telling to change the file's path to this [../scripts/empty-sample.groovy]

**Comment by maggiolo00** [comment]
by seeing other configuration in the gremlin server should be
`[scripts/empty-sample.groovy]`

**Comment by Akshay-15mca1098** [comment]
I tried with the changes error was not getting but also server is not started
![image](https://user-images.githubusercontent.com/29207885/41594691-dc60eab6-73e1-11e8-8eec-d395504dccc6.png)

**Comment by maggiolo00** [comment]
I had no problem on my system.
![screen shot 2018-06-19 at 14 27 09](https://user-images.githubusercontent.com/98812/41597147-e97793d6-73cc-11e8-9561-90237141b6cd.png)

Can you run `kill -3 <pid>` of the Gremlin Server and paste here the thread dump?

Thanks

**Comment by Akshay-15mca1098** [comment]
no such process is shown when i kill the pid

**Comment by maggiolo00** [comment]
After `kill -3 8182`

you should check the logs in GremlinServer terminal or logs

**Comment by Akshay-15mca1098** [comment]
```
admin-12@admin:~$ kill -3 8182
bash: kill: (8182) - No such process

```
no process is there

**Comment by Akshay-15mca1098** [comment]
server struck after this process
![image](https://user-images.githubusercontent.com/29207885/41612223-ddcc5402-740f-11e8-9bf6-7d8b1869ec2b.png)

**Comment by Akshay-15mca1098** [comment]
did you download the jar files from this command 
`bin/gremlin-server.sh -i com.orientechnologies orientdb-gremlin 3.0.2`

**Comment by maggiolo00** [comment]
@Akshay-15mca1098 

```
admin-12@admin:~$ kill -3 8182
bash: kill: (8182) - No such process
```

you can run `jps` to quickly find the pid of the gremlin server

**Comment by maggiolo00** [comment]
@Akshay-15mca1098 

yes i fixed it and i was able to install the plugin with 

```
bin/gremlin-server.sh -i com.orientechnologies orientdb-gremlin 3.0.2
```

**Comment by Akshay-15mca1098** [comment]
I don't know why its the server is not started on my system.

I have posted a question on StackOverflow with the current configuration. one of the gremlin people has responded and he said I messed up some version. I shared you the link can you check.
[](https://stackoverflow.com/questions/50926464/graphfactory-could-not-find-gremlin-graph-property-configration)

**Comment by maggiolo00** [comment]
@Akshay-15mca1098 

the error posted on StackOverflow has been resolved using OrientFactory.

Now let's try to find the reason for the stuck.

**Comment by maggiolo00** [comment]
Can you share the entire startup log?

**Comment by Akshay-15mca1098** [comment]
valid point, I think I should download Gremlin Server 3.3.0

**Comment by Akshay-15mca1098** [comment]
@maggiolo00 
Can you share the entire startup log?

```
admin-12@admin:~/Documents/apache-tinkerpop-gremlin-server-3.3.0/bin$ ./gremlin-server.sh conf/gremlin-server-orientdb.yaml
[INFO] GremlinServer - 
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----

[INFO] GremlinServer - Configuring Gremlin Server from conf/gremlin-server-orientdb.yaml
[INFO] MetricManager - Configured Metrics ConsoleReporter configured with report interval=180000ms
[INFO] MetricManager - Configured Metrics CsvReporter configured with report interval=180000ms to fileName=/tmp/gremlin-server-metrics.csv
[INFO] MetricManager - Configured Metrics JmxReporter configured with domain= and agentId=
[INFO] MetricManager - Configured Metrics Slf4jReporter configured with interval=180000ms and loggerName=org.apache.tinkerpop.gremlin.server.Settings$Slf4jReporterMetrics
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: Detected limit of amount of simultaneously open files is 4096,  limit of open files for disk cache will be set to 1536
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
WARNING: Value of limit of simultaneously open files is too small, recommended value is 262144
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: 12455534592 B/11878 MB/11 GB of physical memory were detected on machine
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: Soft memory limit for this process is set to -1 B/-1 MB/-1 GB
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: Hard memory limit for this process is set to -1 B/-1 MB/-1 GB
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: Path to 'memory' cgroup is '/user.slice'
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: Mounting path for memory cgroup controller is '/sys/fs/cgroup/memory'
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: cgroup soft memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: cgroup hard memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: Detected memory limit for current process is 12455534592 B/11878 MB/11 GB
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: JVM can use maximum 455MB of heap memory
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: Because OrientDB is running outside a container 2g of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=9,375MB (heap=455MB os=11,878MB)
[INFO] DefaultGraphManager - Graph [graph] was successfully configured via [conf/orientdb-empty.properties].
[INFO] ServerGremlinExecutor - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
[INFO] ServerGremlinExecutor - Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
Jun 19, 2018 11:09:24 PM com.orientechnologies.common.log.OLogManager log
INFO: Storage 'memory:test-0.38097554958960267' is created under OrientDB distribution : 3.0.2 - Veloce (build e47e693f1470a7a642461be26983d4eca70777fd, branch develop)
```

**Comment by Akshay-15mca1098** [comment]
Hi @maggiolo00 
did you put database, username, and password in the `orientdb-empty.properties` file.

**Comment by Akshay-15mca1098** [comment]
now i am getting some different error, when i am not putting the DB name, username and password it gets the below error
```
[ERROR] GremlinServer - Gremlin Server Error
java.lang.IllegalStateException: Could not create/configure Authenticator null
	at org.apache.tinkerpop.gremlin.server.AbstractChannelizer.createAuthenticator(AbstractChannelizer.java:185)
	at org.apache.tinkerpop.gremlin.server.AbstractChannelizer.init(AbstractChannelizer.java:134)
	at org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer.init(WebSocketChannelizer.java:60)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.start(GremlinServer.java:151)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.main(GremlinServer.java:326)
Caused by: java.lang.ClassNotFoundException: com.orientechnologies.tinkerpop.server.auth.OGremlinServerAuthenticator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.tinkerpop.gremlin.server.AbstractChannelizer.createAuthenticator(AbstractChannelizer.java:179)
	... 4 more
[ERROR] GremlinServer - Gremlin Server was unable to start and will now begin shutdown: Could not create/configure Authenticator null
```

**Comment by maggiolo00** [comment]
@Akshay-15mca1098 

this is not correct 

`./gremlin-server.sh -i com.orientechnologies orientdb-gremlin-server 3.0.2`

This is the right one

`./gremlin-server.sh -i com.orientechnologies orientdb-gremlin 3.0.2`

Can you please share the orientdb-empty.properties that you are using when the server is not starting?

And remove the  custom authenticator

From the YAML
```
authentication: {
  authenticator: com.orientechnologies.tinkerpop.server.auth.OGremlinServerAuthenticator
    }
```

**Comment by Akshay-15mca1098** [comment]
`./gremlin-server.sh -i com.orientechnologies orientdb-gremlin-server 3.0.2` but this also download the jar fiiles
orientdb-empty.properties
```
gremlin.graph=org.apache.tinkerpop.gremlin.orientdb.OrientFactory
orient-db-name=db
orient-user=root		
orient-pass=root
```

**Comment by Akshay-15mca1098** [comment]
Yaa it's working fine
thanks a lot man

**Comment by maggiolo00** [comment]
Cool!
